stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true            
            blameable: true            
            loggable: true
            sluggable: false
            sortable: false
            tree: false
            uploadable: false