version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: rental-car-flow-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://rental_user:rental_pass@postgres:5432/rental_car_flow_db
      - APP_ENV=dev

  nginx:
    image: nginx:alpine
    container_name: rental-car-flow-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:15
    container_name: rental-car-flow-postgres
    environment:
      POSTGRES_DB: rental_car_flow_db
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: rental-car-flow-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  postgres_data:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
